// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbKDXf_B3WebVx84fT1YLF0XdnhKF3iCA',
    appId: '1:505473993862:web:cf40ec392185710f9b1507',
    messagingSenderId: '505473993862',
    projectId: 'inven3os',
    authDomain: 'inven3os.firebaseapp.com',
    storageBucket: 'inven3os.appspot.com',
    measurementId: 'G-J23KBCBTLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcuI4Jo0yK0zM9Vixv0GVWD61n_vPBZLI',
    appId: '1:505473993862:android:0df94225b0d526189b1507',
    messagingSenderId: '505473993862',
    projectId: 'inven3os',
    storageBucket: 'inven3os.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZF1QHnDLxVc6FNyUYF9FJMqSocASy_Rs',
    appId: '1:505473993862:ios:b75839a7258f04799b1507',
    messagingSenderId: '505473993862',
    projectId: 'inven3os',
    storageBucket: 'inven3os.appspot.com',
    iosBundleId: 'com.example.inven3io',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZF1QHnDLxVc6FNyUYF9FJMqSocASy_Rs',
    appId: '1:505473993862:ios:b75839a7258f04799b1507',
    messagingSenderId: '505473993862',
    projectId: 'inven3os',
    storageBucket: 'inven3os.appspot.com',
    iosBundleId: 'com.example.inven3io',
  );
}
